---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: _data
  label: Data
  create: documents
  match: "**/*"
  new_doc_ext: json
  templates:
  - nav-menu-items
- type: directory
  path: ''
  label: Pages
  create: documents
  match: "*.md"
  exclude: "{README.md}"
  templates:
  - page-builder
- type: directory
  path: posts
  label: Posts
  create: documents
  match: "**/*"
upload_dir: sip
public_path: https://res.cloudinary.com/zheisey/image/upload/f_auto,q_auto,dpr_auto
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
